### ISSUE TITLE
roadmap for google auth middleware

### ISSUE THREAD

**Issue by i10416** [davenverse/googleapis-http4s-runtime#20]
https://github.com/davenverse/googleapis-http4s-runtime/pull/25 contains the following changes

-  https://github.com/davenverse/googleapis-http4s-runtime/pull/10
-  https://github.com/davenverse/googleapis-http4s-runtime/pull/11
-  https://github.com/davenverse/googleapis-http4s-runtime/pull/19
    - https://github.com/davenverse/googleapis-http4s-runtime/pull/17
    - https://github.com/davenverse/googleapis-http4s-runtime/pull/15
- implement application default credentials lookup mechanism: https://google.aip.dev/auth/4110
    - https://github.com/davenverse/googleapis-http4s-runtime/pull/22 

-  [x] compute engine credentials
        - Default Credentials For Google Cloud Virtual Environments: https://google.aip.dev/auth/4115 
        - https://github.com/i10416/googleapis-http4s-runtime/pull/15 https://github.com/armanbilge/gcp4s/blob/2ac68bbf2f06e749205566fbf8690dc276ed1d26/core/shared/src/main/scala/gcp4s/ComputeMetadata.scala
        -  
        - https://github.com/armanbilge/gcp4s/blob/2ac68bbf2f06e749205566fbf8690dc276ed1d26/core/shared/src/main/scala/gcp4s/auth/GoogleCredentials.scala#L121

TODOs
- [ ] service account credentials(https://google.aip.dev/auth/4112)
- [ ] aws credentials(part of https://google.aip.dev/auth/4117)
    - https://github.com/davenverse/googleapis-http4s-runtime/pull/12

Note: service account credentials and AWS credentials need crypto dependencies. Should we use https://github.com/http4s/http4s-crypto/ ?

**Comment by i10416** [comment]
Artifacts under my organization support user credentials auth now.


```scala
//> using scala "2.13.12"
//> using repositories "sonatype-s01:snapshots"
//> using dep "dev.i10416::http4s-googleapis-runtime:0.0-20544fa-SNAPSHOT"
//> using dep "org.http4s::http4s-core:0.23.25"
//> using dep "org.http4s::http4s-ember-client:0.23.25"
//> using dep "org.typelevel::cats-effect:3.5.2"

import cats.effect._
import org.http4s.ember.client.EmberClientBuilder
import org.http4s.googleapis.runtime.auth.ApplicationDefaultCredentials
object Main extends IOApp {
  def run(args: List[String]): IO[ExitCode] = EmberClientBuilder
    .default[IO]
    .build
    .use { client =>
      for {
        oauth2 <- ApplicationDefaultCredentials(client)
        tkn <- oauth2.get
        _ <- IO.println(tkn)
      } yield ()

    }
    .handleErrorWith(IO.println(_))
    .as(ExitCode.Success)
}

```

**Comment by i10416** [comment]
artifacts 0.0-2f88c52-SNAPSHOT now support workload identity federation auth.

These are the example to authenticate from GitHub Actions.

```scala
//> using scala "2.13.12"
//> using repositories "sonatype-s01:snapshots"
//> using dep "dev.i10416::http4s-googleapis-runtime:0.0-2f88c52-SNAPSHOT"
//> using dep "org.http4s::http4s-core:0.23.25"
//> using dep "org.http4s::http4s-ember-client:0.23.25"
//> using dep "org.typelevel::cats-effect:3.5.2"

import cats.effect._
import org.http4s.ember.client.EmberClientBuilder
import org.http4s.googleapis.runtime.auth.ApplicationDefaultCredentials
object Main extends IOApp {
  def run(args: List[String]): IO[ExitCode] = EmberClientBuilder
    .default[IO]
    .build
    .use { client =>
      for {
        oauth2 <- ApplicationDefaultCredentials(client)
        tkn <- oauth2.get
        _ <- IO.println(tkn)
      } yield ()

    }
    .as(ExitCode.Success)
}
```

```yaml
name: 'Debug Google OAuth2 External Account Credentials'

on:    
  pull_request:
    branches: [master, main]
    types:
      - opened
      - synchronize
      - reopened
jobs:
  check:
    runs-on: ubuntu-20.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Authenticate to Google Cloud
        id: 'google-cloud-auth'
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: GCP_WORKLOAD_ID_PROVIDER_ID
          service_account: GCP_SERVICE_ACCOUNT
          create_credentials_file: true
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - uses: coursier/cache-action@v6.3
      - uses: VirtusLab/scala-cli-setup@main
      - run: scala-cli .
```

**Comment by i10416** [comment]
snapshot 0.0-c78837d-SNAPSHOT supports compute engine credentials(not tested yet).
https://github.com/i10416/googleapis-http4s-runtime/pull/15

**Comment by i10416** [comment]
There is another Google auth library. Perhaps, we can borrow some idea and design from it.
https://github.com/permutive-engineering/gcp-auth
